project:
  type: website
  output-dir: docs

website:
  title: "jurgsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - comptest.qmd
      - presi.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
    freeze: auto
